[package]
name = "brush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = { path = "../burn/crates/burn", features = ['wgpu', 'autodiff'] }
bytemuck = "1.14.3"
derive-new = "0.6.0"
rerun = "0.13.0"
