[package]
name = "brush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22"

burn = { path = "../burn/crates/burn", features = ['wgpu', 'autodiff'] }
burn-compute = { path = "../burn/crates/burn-compute" }
burn-jit = { path = "../burn/crates/burn-jit" }
burn-wgpu = { path = "../burn/crates/burn-wgpu" }

bytemuck = "*"
derive-new = "*"
ndarray = "*"
rerun = { version = "0.14.1" }
image = { version = "0.24", default-features = false, features = [
    'png',
    'webp',
] }
serde = "*"
serde_json = "*"
rand = "0.8.5"
anyhow = "1.0.81"
wgpu = "0.19"

[build-dependencies]
wgsl_bindgen = { path = "../wgsl-bindgen/wgsl_bindgen" }


[profile.dev]
opt-level = 1   # Make debug builds run faster
panic = "abort" # This leads to better optimizations and smaller binaries (and is the default in Wasm anyways).

[profile.dev.build-override]
debug = true # enable debug symbols for build scripts when building in dev (codegen backtraces!)

# Optimize all dependencies even in debug builds (does not affect workspace packages):
[profile.dev.package."*"]
opt-level = 2

[profile.release]
# debug = true # good for profilers
panic = "abort" # This leads to better optimizations and smaller binaries (and is the default in Wasm anyways).
