[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = ["crates/*"]
default-members = ["crates/brush"]

[workspace.package]
edition = "2021"
version = "0.1.0"
readme = "README.md"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.dependencies]
glam = "0.22"

burn = { git = "https://github.com/tracel-ai/burn.git", default-features = false, features = [
    'wgpu',
    'autodiff',
    'template',
    "std",
] }
burn-compute = { git = "https://github.com/tracel-ai/burn.git", default-features = false }
burn-jit = { git = "https://github.com/tracel-ai/burn.git", default-features = false }
burn-wgpu = { git = "https://github.com/tracel-ai/burn.git", default-features = false }
burn-cube = { git = "https://github.com/tracel-ai/burn.git", default-features = false }

bytemuck = "1.15"
ndarray = "0.15"

image = { version = "0.25", default-features = false, features = [
    'png',
    'webp',
] }

serde = "1.0"
serde_json = "1.0"
rand = "0.8.5"
anyhow = "1.0.81"
wgpu = { version = "0.20", features = ["naga"] }
naga_oil = "0.14"
naga = "0.20"
running-average = "0.1.0"
ply-rs = "0.1.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
egui = { git = "https://github.com/emilk/egui.git" }
eframe = { git = "https://github.com/emilk/egui.git", default-features = false, features = [
    "wgpu",
] }
egui_extras = { git = "https://github.com/emilk/egui.git", default-features = false, features = [
    "all_loaders",
] }
assert_approx_eq = "1.1.0"
safetensors = "0.4.3"

# Build dependencies.
miette = { version = "7.2.0", features = ["fancy"] }

thiserror = "*"

[profile.dev]
panic = "abort" # This leads to better optimizations and smaller binaries (and is the default in Wasm anyways).

# Optimize all dependencies even in debug builds (does not affect workspace packages):
[profile.dev.package."*"]
opt-level = 2

[profile.release]
# debug = true # good for profilers
panic = "abort" # This leads to better optimizations and smaller binaries (and is the default in Wasm anyways).
