[package]
name = "brush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22"

burn = { path = "../burn/crates/burn", features = [
    'wgpu',
    'ndarray',
    'autodiff',
] }
bytemuck = "1.14.3"
derive-new = "0.6.0"
ndarray = "0.15.6"
rerun = { version = "0.14.0" }
image = { version = "0.24", default-features = false, features = [
    'png',
    'webp',
] }
serde = "1.0.197"
serde_json = "1.0.114"
rand = "0.8.5"
anyhow = "1.0.81"
wgpu = "0.19"
[build-dependencies]
wgsl_bindgen = "0.10.0"


[profile.dev]
opt-level = 1   # Make debug builds run faster
panic = "abort" # This leads to better optimizations and smaller binaries (and is the default in Wasm anyways).

[profile.dev.build-override]
debug = true # enable debug symbols for build scripts when building in dev (codegen backtraces!)

# Optimize all dependencies even in debug builds (does not affect workspace packages):
[profile.dev.package."*"]
opt-level = 2

[profile.release]
# debug = true # good for profilers
panic = "abort" # This leads to better optimizations and smaller binaries (and is the default in Wasm anyways).
