[package]
name = "brush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22"

burn = { path = "../burn/crates/burn", features = [
    'wgpu',
    'autodiff',
    'template',
] }
burn-compute = { path = "../burn/crates/burn-compute" }
burn-jit = { path = "../burn/crates/burn-jit" }
burn-wgpu = { path = "../burn/crates/burn-wgpu" }

bytemuck = "1.14.3"
derive-new = "0.6.0"
ndarray = "0.15.6"
rerun = { version = "0.14.0", default-features = false, features = [
    'sdk',
    'glam',
], optional = true }

image = { version = "0.24", default-features = false, features = [
    'png',
    'webp',
] }


tracing-tracy = { version = "0.11.0", optional = true }
serde = "1.0.197"
serde_json = "1.0.114"
rand = "0.8.5"
anyhow = "1.0.81"
wgpu = { version = "0.18", features = ["naga"] }
naga_oil = "0.11"
naga = { version = "0.14.2", feature = ["wgsl-out"] }
miette = "7.2.0"
running-average = "0.1.0"
ply-rs = "0.1.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
egui = "0.25.0"
eframe = { version = "0.25.0", features = ["wgpu"] }


[features]
tracy = ["dep:tracing-tracy"]
rerun = ["dep:rerun"]


[build-dependencies]
wgsl_bindgen = { path = "../wgsl-bindgen/wgsl_bindgen" }
miette = { version = "7.2.0", features = ["fancy"] }

[profile.dev]
opt-level = 1   # Make debug builds run faster
panic = "abort" # This leads to better optimizations and smaller binaries (and is the default in Wasm anyways).

[profile.dev.build-override]
debug = true # enable debug symbols for build scripts when building in dev (codegen backtraces!)

# Optimize all dependencies even in debug builds (does not affect workspace packages):
[profile.dev.package."*"]
opt-level = 2

[profile.release]
# debug = true # good for profilers
panic = "abort" # This leads to better optimizations and smaller binaries (and is the default in Wasm anyways).
