[package]
name = "brush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = { path = "../burn/crates/burn", features = [
    'wgpu',
    'ndarray',
    'autodiff',
] }
bytemuck = "1.14.3"
derive-new = "0.6.0"
ndarray = "0.15.6"
rerun = { version = "0.13.0" }
image = { version = "0.24", default-features = false, features = [
    'png',
    'webp',
] }

[profile.dev]
opt-level = 1
incremental = true
