[package]
name = "brush"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { workspace = true }
image = { workspace = true }


burn = { workspace = true }
burn-compute = { workspace = true }
burn-jit = { workspace = true }
burn-wgpu = { workspace = true }
burn-cube = { workspace = true }


# Optional dependencies which can't live in the workspace root.
rerun = { version = "0.16", default-features = false, features = [
    'sdk',
    'glam',
], optional = true }

tracing-tracy = { version = "0.11.0", optional = true }

# Brush deps.
brush-sort = { path = "../brush-sort" }
brush-prefix-sum = { path = "../brush-prefix-sum" }

bytemuck = "1.15"
ndarray = "0.15"

serde = "1.0"
serde_json = "1.0"
rand = "0.8.5"
anyhow = "1.0.81"
wgpu = { version = "0.20", features = ["naga"] }
naga_oil = "0.14"
naga = "0.20"
miette = "7.2.0"
running-average = "0.1.0"
ply-rs = "0.1.3"
tracing = { workspace = true }
tracing-subscriber = "0.3.18"
egui = { git = "https://github.com/emilk/egui.git", rev = "1888d19" }
eframe = { git = "https://github.com/emilk/egui.git", rev = "1888d19", features = [
    "wgpu",
] }
egui_extras = { git = "https://github.com/emilk/egui.git", rev = "1888d19", features = [
    "all_loaders",
] }
assert_approx_eq = "1.1.0"
safetensors = "0.4.3"
brush-kernel = { version = "0.1.0", path = "../brush-kernel" }

[features]
tracy = ["dep:tracing-tracy"]
sync_tracy = []
rerun = ["dep:rerun"]
default = ["tracy", "rerun"]

[build-dependencies]
wgsl_bindgen = { git = "https://github.com/ArthurBrussee/wgsl-bindgen.git", branch = "updates" }
miette = { version = "7.2.0", features = ["fancy"] }
