[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# The output dir for all final assets.
dist = "trunk_dist"
# Allow disabling sub-resource integrity (SRI)
no_sri = true
